hotels_rails/config/routes.rb
HotelsRails::Application.routes.draw do
  resources :users

  resources :rooms

  resources :hotels

	match '/showRooms/:id' => 'users#show'
	match '/signup' => 'users#signup'
	match '/signin' => 'users#signin'
	match '/checkUser' => 'users#checkUser'
	match '/logout' => 'users#logout'
	match '/search' => 'users#search'
	match '/showRooms/:id/chooseDate' => 'users#chooseDate'
	match '/showRooms/:id/showAvailableRooms/' => 'users#showAvailableRooms'
	match '/book' => 'users#book'
	match '/addComment' => 'users#addComment'
	match '/showRooms/' => 'users#show'
	match '/searchByName/' => 'users#searchByName'

end

hotels_rails/app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :hotel
	validates :room_price ,confirmation:true,:presence => true
	validates :img ,confirmation:true,:presence => true
	validates :hotel_id ,confirmation:true,:presence => true
end

hotels_rails/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
		if cookies[:admin]
				@rooms = Room.all
			  respond_to do |format|
					format.html # index.html.erb
				  format.json { render json: @rooms }
				end
		else
		  		redirect_to users_url
		end
	end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
		if cookies[:admin]
		  @room = Room.find(params[:id])
		  respond_to do |format|
		    format.html # show.html.erb
		    format.json { render json: @room }
		  end
		else
		  		redirect_to users_url
		end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
		if cookies[:admin]
		  @room = Room.new
		  respond_to do |format|
		    format.html # new.html.erb
		    format.json { render json: @room }
		  end
		else
		  		redirect_to users_url
		end
  end

  # GET /rooms/1/edit
  def edit
		if cookies[:admin]
    	@room = Room.find(params[:id])
		else
		  		redirect_to users_url
		end
  end

  # POST /rooms
  # POST /rooms.json
  def create
		if cookies[:admin]
		  @room = Room.new(params[:room])
		  respond_to do |format|
		    if @room.save
		      format.html { redirect_to @room, notice: 'Room was successfully created.' }
		      format.json { render json: @room, status: :created, location: @room }
		    else
		      format.html { render action: "new" }
		      format.json { render json: @room.errors, status: :unprocessable_entity }
		    end
    end
		else
		  		redirect_to users_url
		end
  end


  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
		if cookies[:admin]
		  @room = Room.find(params[:id])
		  respond_to do |format|
		    if @room.update_attributes(params[:room])
		      format.html { redirect_to @room, notice: 'Room was successfully updated.' }
		      format.json { head :no_content }
		    else
		      format.html { render action: "edit" }
		      format.json { render json: @room.errors, status: :unprocessable_entity }
		    end
		  end
		else
		  		redirect_to users_url
		end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
		if session[:admin]
		  @room = Room.find(params[:id])
		  @room.destroy

		  respond_to do |format|
		    format.html { redirect_to rooms_url }
		    format.json { head :no_content }
		  end
		end
	else
		redirect_to users_url
	end

end

hotels_rails/app/helpers/rooms_helper.rb
module RoomsHelper
end

hotels_rails/app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel_id %><br />
    <%= f.number_field :hotel_id %>
  </div>
  <div class="field">
    <%= f.label :room_price %><br />
    <%= f.number_field :room_price %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hotels_rails/app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

hotels_rails/app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Hotel</th>
    <th>Room price</th>
    <th>Img</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.hotel_id %></td>
    <td><%= room.room_price %></td>
    <td><%= room.img %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

hotels_rails/app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

hotels_rails/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hotel:</b>
  <%= @room.hotel_id %>
</p>

<p>
  <b>Room price:</b>
  <%= @room.room_price %>
</p>

<p>
  <b>Img:</b>
  <%= @room.img %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>