hotels_rails/config/routes.rb
HotelsRails::Application.routes.draw do
  resources :users

  resources :rooms

  resources :hotels

	match '/showRooms/:id' => 'users#show'
	match '/signup' => 'users#signup'
	match '/signin' => 'users#signin'
	match '/checkUser' => 'users#checkUser'
	match '/logout' => 'users#logout'
	match '/search' => 'users#search'
	match '/showRooms/:id/chooseDate' => 'users#chooseDate'
	match '/showRooms/:id/showAvailableRooms/' => 'users#showAvailableRooms'
	match '/book' => 'users#book'
	match '/addComment' => 'users#addComment'
	match '/showRooms/' => 'users#show'
	match '/searchByName/' => 'users#searchByName'

end

hotels_rails/app/models/user.rb
class User < ActiveRecord::Base
	validates :name ,confirmation:true,:presence => true
	validates :email ,confirmation:true,:presence => true
	validates :password ,confirmation:true,:presence => true
	validates :phone ,confirmation:true,:presence => true
end

hotels_rails/app/controllers/users_controller.rb
require 'digest/md5'

class UsersController < ApplicationController
  
	# GET /users
  def index
    @hotels = Hotel.all
    respond_to do |format|
      format.html
		end
  end

	#***************get all rooms in specific hotel****************#
  def show
		if params.has_key?(:id)
			if cookies.has_key?(:hotel_id)
					cookies.delete(:hotel_id)
			end
			cookies[:hotel_id] = params[:id]
		  @rooms = Room.find(:all,:conditions => { :hotel_id => params[:id]})
			@comments = Comment.find(:all,:conditions => { :hotel_id => params[:id]})
		else
			@rooms = Room.find(:all,:conditions => { :hotel_id => cookies[:hotel_id]})
			@comments = Comment.find(:all,:conditions => { :hotel_id => cookies[:hotel_id]})
		end
    respond_to do |format|
      format.html 
    end
  end

	#**************get user info*****************#
  def signup
    @user = User.new

    respond_to do |format|
      format.html
    end
  end
	
	#**************save user info*****************#
  def create
		hashed_password = Digest::MD5.hexdigest(params[:user][:password])
		@user = User.new({'name' => params[:user][:name],'email' => params[:user][:email],'password' => hashed_password,'phone' => params[:user][:phone]})
    respond_to do |format|
      if @user.save
        format.html { redirect_to signin_url, notice: 'User was successfully created.' }
      else
        format.html { render action: "signup" }
      end
    end
  end
 

	#****************signin***************#
	def signin
		respond_to do |format|
		  format.html # new.html.erb
		end
  	end

	#****************Authentication***************#
	def checkUser
		@user_auth = User.find(:all,:conditions => { :email => params[:email],:password => Digest::MD5.hexdigest(params[:password])})
		if !@user_auth.empty?
			user =  @user_auth[0]
			cookies[:user_id] =user.id
			cookies[:user_name] = user.name
			cookies[:admin] = user.admin
			redirect_to users_url
		else
			redirect_to signup_url
		end
  end


	#****************logout***************#
	def logout 
      cookies.delete(:user_name)
			cookies.delete(:user_id)
			cookies.delete(:admin)
			redirect_to users_url
  end

	#****************search***************#
	def search
      @hotels = Hotel.find(:all,:conditions => { :city => params[:city],:region => params[:region]})
			respond_to do |format|
        format.html    
    	end
  	end

	#****************Choose date***************#
	def chooseDate
		if cookies.has_key?(:user_name) 
			if cookies.has_key?(:hotel_id)
					cookies.delete(:hotel_id)
			end
			cookies[:hotel_id] = params[:id]
			respond_to do |format|
				format.html    
			end

		else
			redirect_to signin_url
		end
  end
 

 #***************get available rooms in specific hotel****************#
	def showAvailableRooms 
		if cookies.has_key?(:chkin)
				cookies.delete(:chkin)
				cookies.delete(:chkout)
		end
		cookies[:chkin] = params[:chkin]
		cookies[:chkout] = params[:chkout]

		@rooms = Room.find_by_sql ["SELECT * FROM rooms WHERE hotel_id = ? and id NOT IN (SELECT room_id FROM bookings WHERE hotel_id=(?) and (chkin between ? and ?) or (chkout between ? and ?) )", cookies[:hotel_id],cookies[:hotel_id],cookies[:chkin],cookies[:chkout],cookies[:chkin],cookies[:chkout]]

		respond_to do |format|
		  format.html 
		end
	end 


	#***************Book****************#
	def book
		if request.post?
			@rooms = params[:room]
			@rooms.each do |room|   
				Booking.new(:user_id => cookies[:user_id],:hotel_id => cookies[:hotel_id] ,:room_id => room,:chkin => cookies[:chkin],:chkout => cookies[:chkout]).save
			end
		else
			respond_to do |format|
					format.html 
			end
		end
	end 

#***************Comment****************#
	def addComment
		if request.post?
			room_id = params[:room_id]
			hotel_id = params[:hotel_id]
			comment = params[:comment]
			Comment.new(:user_id => cookies[:user_id],:user_name => cookies[:user_name],:hotel_id => hotel_id ,:room_id => room_id,:comment => comment).save
			redirect_to '/showRooms'
		end			
	end 


end

hotels_rails/app/helpers/users_helper.rb
module UsersHelper
end

hotels_rails/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hotels_rails/app/views/users/book.html.erb
<h3>We are Watting for u :D </h3>

<a href ='/users'> Back Home </a>

hotels_rails/app/views/users/chooseDate.html.erb
<h1>Choose Date</h1>
<a href ='/users'> Back Home </a>
<form method="post" action="showAvailableRooms">
	Checkin date:<input type="date" name="chkin"><br>
	Checkout date:<input type="date" name="chkout"><br>
	<input type="submit" value="Submit" id="button">
</form>

<script>
	var button = document.getElementById('button')
	var chkin = document.getElementsByName('chkin')[0]
	var chkout = document.getElementsByName('chkout')[0]
	button.onclick = function(event) {
		if (chkout.value == "" | chkin.value == ""){
        event.preventDefault()
				alert('Choose date Please')
		}
	}
</script>

hotels_rails/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

hotels_rails/app/views/users/index.html.erb
<h1>Home Page</h1>
<% if cookies.has_key?(:user_name) %>
		<%= cookies[:user_name] %>
		<%= link_to 'Logout', logout_path %>
<% else %>
	<%= link_to 'SignUp', signup_path %>
	<%= link_to 'SignIn', signin_path %>
<% end %>


 <ul>
<% @hotels.each do |hotel| %>
    <li> <%= hotel.name %> <a href=showRooms/<%= hotel.id %>>list rooms</a></li>
<% end %>
</ul>

<br/>


<form method="GET" action="search">
	City:<input type="text" name="city">
	Region:<input type="text" name="region">
	<input type="submit" value="Search" id="button1">
</form>

<script>
	var button1 = document.getElementById('button1')
	var city = document.getElementsByName('city')[0]
	var region = document.getElementsByName('region')[0]
	button1.onclick = function(event) {
		if (city.value == "" | region.value == ""){
        event.preventDefault()
				alert('Enter all data Please')
		}
	}
</script>

hotels_rails/app/views/users/search.html.erb
<h1>Home Page</h1>
<a href ='/users'> Back Home </a>
 <ul>
<% @hotels.each do |hotel| %>
    <td> <%= hotel.name %> <a href=showRooms/<%= hotel.id %>/chooseDate>book a room</a></td>
<% end %>
</ul>
<br />

hotels_rails/app/views/users/show.html.erb
<title>Rooms</title>
<a href ='/users'> Back Home </a>
<% if !@rooms.empty? %>
<ul>
<% @rooms.each do |room| %>
  <li>
	Price per night: <%= room.room_price %>$<br><br>
    <img src="<%= room.img %>" ></img><br><br>

	<% if cookies.has_key?(:user_name) %>
		<% @comments.each do |comment| %>
			<% if comment.room_id == room.id %>
				<strong><%= comment.user_name %></strong>
				<p><%= comment.comment %></p>
				<br>
			<% end %>
		<% end %>
		<form method="POST" action="/addComment">
			<textarea rows="4" cols="50" name="comment"></textarea>
			<input type="hidden" name="room_id" value=<%= room.id %>>
			<input type="hidden" name="hotel_id" value=<%= room.hotel_id %>">
			<br>
			<input type="submit" value="add" id="button">
		</form>
		<br>
	<% end %>
  </li>
<% end %>
</ul>
<% else %>
	<p>No rooms are available </p>
<% end %>
<br />

<script>
	var button = document.getElementById('button')
	var comment = document.getElementsByName('comment')[0]
	button.onclick = function(event) {
		if (comment.value == ""){
        event.preventDefault()
		}
	}
</script>

hotels_rails/app/views/users/showAvailableRooms.html.erb
<h1>Available Rooms</h1>
<a href ='/users'> Back Home </a>
<% if !@rooms.empty? %>
<form method="POST" action="/book">
<% @rooms.each do |room| %>  	
	<input type="checkbox" name="room[]" value=<%= room.id %>><%= room.room_price %>$<br>
    <img src="<%= room.img %>" width="300px" height="200px" ></img><br>  
<% end %>
	<br>
	<input type="submit" value="Book">
</form>
<% else %>
	<p>No rooms are available </p>
<% end %>
<br />

hotels_rails/app/views/users/signin.html.erb
<h1>signin</h1>

<form method="post" action="checkUser">
	E-mail: <input type="email" name="email"><br>
	Password: <input type="password" name="password"><br>
	<input type="submit" value="login" id="button">
</form>

<script>
	var button = document.getElementById('button')
	var email = document.getElementsByName('email')[0]
	var password = document.getElementsByName('password')[0]
	button.onclick = function(event) {
		if (email.value == "" | password.value == ""){
        event.preventDefault()
				alert('Enter all data Please')
		}
	}
</script>

hotels_rails/app/views/users/signup.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>